GET http://localhost:8000/proute
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OWQ2ODUzZjQxM2YxYzhiZmFiYTYxZiIsImlhdCI6MTY4ODAzODI1NX0.gSAWVLWBG7GfiaXa0AHGhSyocDpHTtSBrY2yWPzbAvA
###

POST http://localhost:8000/signin
Content-Type: application/json

{
    "name":"arun",
    "password":"arunakil1234",
    "email":"arunakil12@gmail.com"
}

###


POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"arunakil12@gmail.com",
    "password":"arunakil1234"
}


