GET http://localhost:8000/proute
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmMxOTRhMWYzMTVhOGY1MTRmNjlmZCIsImlhdCI6MTY5NzM4ODg4NH0.Zj_OWDjv7EM6visLbLsEHgn-PA4bE-TYfi55cNvoT18
###

POST http://localhost:8000/signin
Content-Type: application/json

{
    "name":"arun",
    "password":"arunakil1234",
    "email":"arunakil1@gmail.com"
}

###


POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"arunakil1@gmail.com",
    "password":"arunakil1234"
}


